### ISSUE TITLE
Known Issue Tracker

### ISSUE THREAD

**Issue by Zarthus** [Zarthus/liefland#1]
- [ ] Responsiveness leaves much to be desired.
  - [ ] nav bar doesn't work
  - [ ] many pages should be fullwidth on mobile 
- [ ] Links to values, strengths and weaknesses don't work.
- [ ] The "particle effect" is incomplete
- [x] The "particle effect" is not yet implemented.
- [ ] API is not dynamic. #KISS
- [ ] Buttons are bigger than their links, so you can misclick easily.
